name: Docker Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker container
        run: |
          docker compose run --rm operator-mono-lig
          docker run -v $PWD/build:/in -v $PWD/out:/out nerdfonts/patcher -c || true

      - name: Bundle
        run: |
          zip -r with-nerd-fonts.zip out
          zip -r only-lig.zip build
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Release $$'
          prerelease: false
          files: |
            only-lig.zip
            with-nerd-fonts.zip
